"""empty message

Revision ID: 04dcff2188f5
Revises: f64b72bc0d6b
Create Date: 2024-04-20 22:12:53.096947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04dcff2188f5'
down_revision = 'f64b72bc0d6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet_odd', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['game_id'])

    with op.batch_alter_table('open_bet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sport', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('open_bet', schema=None) as batch_op:
        batch_op.drop_column('sport')

    with op.batch_alter_table('bet_odd', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
