"""empty message

Revision ID: 0c8eb0093dc6
Revises: 
Create Date: 2024-02-09 13:52:51.393989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c8eb0093dc6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_information', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('tel_no', sa.String(), nullable=True))
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_information', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('tel_no')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
