"""empty message

Revision ID: 29ab1d958028
Revises: 7e79a5c1eb7c
Create Date: 2024-02-14 21:48:09.751360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29ab1d958028'
down_revision = '7e79a5c1eb7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referrer',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_fk', sa.Integer(), nullable=True),
    sa.Column('commission_rate', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referred_by', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('referred_by')

    op.drop_table('referrer')
    # ### end Alembic commands ###
