"""empty message

Revision ID: 2e0ab404b01f
Revises: e4b839607fae
Create Date: 2024-04-12 18:57:29.370133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e0ab404b01f'
down_revision = 'e4b839607fae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bet_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('casino_partner',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.Column('callback_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('double_or_nothing',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('current_offer', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('open_user_bet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_user_id', sa.String(), nullable=True),
    sa.Column('creator_partner_api_key', sa.String(), nullable=True),
    sa.Column('bet_description', sa.String(), nullable=True),
    sa.Column('bet_amount', sa.Float(), nullable=True),
    sa.Column('opp_amount', sa.Float(), nullable=True),
    sa.Column('offer_expiration_datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partner_session',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('taken_bet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('user_1_id', sa.String(), nullable=True),
    sa.Column('user_1_partner_api_key', sa.String(), nullable=True),
    sa.Column('user_2_id', sa.String(), nullable=True),
    sa.Column('user_2_partner_api_key', sa.String(), nullable=True),
    sa.Column('winner', sa.String(), nullable=True),
    sa.Column('open_user_bet_fk', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bet_coupon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('freebet_amount', sa.Float(), nullable=True))

    with op.batch_alter_table('bet_odd', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bettable', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('market_url', sa.String(), nullable=True))

    with op.batch_alter_table('bet_selected_option', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bet_option_fk', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('odd_locked_in_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('reference_id', sa.String(), nullable=True))

    with op.batch_alter_table('open_bet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_odds', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('live_betting_expired', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('freebet', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('freebet_usable', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('telegram_chat_id', sa.String(), nullable=True))

    with op.batch_alter_table('user_information', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('id_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_information', schema=None) as batch_op:
        batch_op.drop_column('id_verified')
        batch_op.drop_column('gender')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('telegram_chat_id')
        batch_op.drop_column('freebet_usable')
        batch_op.drop_column('freebet')

    with op.batch_alter_table('open_bet', schema=None) as batch_op:
        batch_op.drop_column('live_betting_expired')
        batch_op.drop_column('has_odds')

    with op.batch_alter_table('bet_selected_option', schema=None) as batch_op:
        batch_op.drop_column('reference_id')
        batch_op.drop_column('odd_locked_in_rate')
        batch_op.drop_column('bet_option_fk')

    with op.batch_alter_table('bet_odd', schema=None) as batch_op:
        batch_op.drop_column('market_url')
        batch_op.drop_column('bettable')

    with op.batch_alter_table('bet_coupon', schema=None) as batch_op:
        batch_op.drop_column('freebet_amount')

    op.drop_table('taken_bet')
    op.drop_table('partner_session')
    op.drop_table('open_user_bet')
    op.drop_table('double_or_nothing')
    op.drop_table('casino_partner')
    op.drop_table('bet_transaction')
    # ### end Alembic commands ###
