"""empty message

Revision ID: 35f7e1686dc7
Revises: dc33bf8817e3
Create Date: 2024-02-21 16:58:05.894808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35f7e1686dc7'
down_revision = 'dc33bf8817e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet_selected_option', schema=None) as batch_op:
        batch_op.add_column(sa.Column('match_name_row', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet_selected_option', schema=None) as batch_op:
        batch_op.drop_column('match_name_row')

    # ### end Alembic commands ###
