"""empty message

Revision ID: 4783e45c35d8
Revises: 2b62375c7681
Create Date: 2024-02-20 13:44:05.174502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4783e45c35d8'
down_revision = '2b62375c7681'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competition', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manual_prize_override', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competition', schema=None) as batch_op:
        batch_op.drop_column('manual_prize_override')

    # ### end Alembic commands ###
