"""empty message

Revision ID: 7e79a5c1eb7c
Revises: 4b6570861529
Create Date: 2024-02-12 16:37:01.360878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e79a5c1eb7c'
down_revision = '4b6570861529'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('payment_information_fk', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('payment_unique_number', sa.String(), nullable=True))
        batch_op.drop_column('bank_information_fk')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_information_fk', sa.INTEGER(), nullable=True))
        batch_op.drop_column('payment_unique_number')
        batch_op.drop_column('payment_information_fk')
        batch_op.drop_column('transaction_date')

    # ### end Alembic commands ###
