"""empty message

Revision ID: 818da27c0d8b
Revises: 29ab1d958028
Create Date: 2024-02-15 18:24:57.793190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '818da27c0d8b'
down_revision = '29ab1d958028'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('withdrawal_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('withdraw_to', sa.String(), nullable=True))
        batch_op.drop_column('is_approved')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('withdrawal_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_approved', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('withdraw_to')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
