"""empty message

Revision ID: dc33bf8817e3
Revises: 4783e45c35d8
Create Date: 2024-02-21 15:26:07.113972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc33bf8817e3'
down_revision = '4783e45c35d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bet_coupon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_fk', sa.Integer(), nullable=True),
    sa.Column('total_value', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bet_odd',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=True),
    sa.Column('odd', sa.Float(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('bet_option_fk', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bet_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_name', sa.String(), nullable=True),
    sa.Column('game_details', sa.String(), nullable=True),
    sa.Column('open_bet_fk', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bet_selected_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bet_odd_fk', sa.Integer(), nullable=True),
    sa.Column('bet_coupon_fk', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('open_bet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_match_id', sa.String(), nullable=True),
    sa.Column('bet_ending_datetime', sa.DateTime(), nullable=True),
    sa.Column('league_icon_url', sa.String(), nullable=True),
    sa.Column('match_league', sa.String(), nullable=True),
    sa.Column('team_1', sa.String(), nullable=True),
    sa.Column('team_2', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('open_bet')
    op.drop_table('bet_selected_option')
    op.drop_table('bet_option')
    op.drop_table('bet_odd')
    op.drop_table('bet_coupon')
    # ### end Alembic commands ###
