"""empty message

Revision ID: e4b839607fae
Revises: 35f7e1686dc7
Create Date: 2024-02-21 17:03:21.932032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4b839607fae'
down_revision = '35f7e1686dc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet_option', schema=None) as batch_op:
        batch_op.add_column(sa.Column('match_name_row', sa.String(), nullable=True))

    with op.batch_alter_table('bet_selected_option', schema=None) as batch_op:
        batch_op.drop_column('match_name_row')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet_selected_option', schema=None) as batch_op:
        batch_op.add_column(sa.Column('match_name_row', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('bet_option', schema=None) as batch_op:
        batch_op.drop_column('match_name_row')

    # ### end Alembic commands ###
