"""empty message

Revision ID: f64b72bc0d6b
Revises: 2e0ab404b01f
Create Date: 2024-04-14 00:02:07.642198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f64b72bc0d6b'
down_revision = '2e0ab404b01f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet_selected_option', schema=None) as batch_op:
        batch_op.add_column(sa.Column('match_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('game_name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet_selected_option', schema=None) as batch_op:
        batch_op.drop_column('game_name')
        batch_op.drop_column('match_name')

    # ### end Alembic commands ###
